theme = "Ayu Light"
theme-dark = "Twilight"

background-opacity = 0.6

font-family = "Sligoil Micro NF"
font-size = 14
cursor-style = "underline"
text-underline = false

sidebar-width = 246

cursor-animation = "smooth"

open-with-app = "Xcode|com.apple.dt.Xcode"
open-with-app = "Zed|dev.zed.Zed"
