- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.config/kitty: kitty
    ~/.config/sheldon: sheldon
    ~/.gitconfig:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [ln -sf ~/.dotfiles/vim-pathogen/autoload/pathogen.vim ~/.vim/autoload/pathogen.vim, Link vim pathogen]
