- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.gitconfig:
    ~/.hyper.js:
    ~/.oh-my-zsh:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:

- shell:
  - [git submodule update --init --recursive, Installing submodules]
