- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.config/compton.conf: config/compton.conf
    ~/.config/conky: config/conky
    ~/.config/openbox: config/openbox
    ~/.config/tint2/tint2rc: config/tint2
    ~/.gitconfig:
    ~/.hyper.js:
    ~/.ncmpcpp/config: ncmpcpp
    ~/.oh-my-zsh:
    ~/.Xresources:
    ~/.zsh:
    ~/.zshrc:

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  # - [ln -s ~/.zsh/plugins/pure/pure.zsh /usr/local/share/zsh/site-functions/prompt_pure_setup, Link pure prompt]
  # - [ln -s ~/.zsh/plugins/pure/async.zsh /usr/local/share/zsh/site-functions/async, Link async for pure prompt]
