brew "bat"
brew "btop"
brew "oven-sh/bun/bun", trusted: true
brew "bjarneo/cliamp/cliamp", trusted: true
brew "diffnav"
brew "eza"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "eugene-babichenko/fixit/fixit", trusted: true
brew "fnm"
brew "fzf"
brew "git-delta"
brew "glow"
brew "mas"
brew "mole"
brew "can1357/tap/omp", trusted: true
brew "pnpm"
brew "ripgrep"
brew "scrcpy"
brew "sheldon"
brew "stow"
brew "tealdeer"
brew "tmux"
brew "zoxide"

cask "airsync"
cask "audacity"
cask "aya"
cask "batfi"
cask "TheBoredTeam/boring-notch/boring-notch", trusted: true, args: { install_options: ["--no-quarantine"] }
cask "calendr"
cask "caskhub"
cask "deskpad"
cask "ente-auth"
cask "xykong/tap/flux-markdown", trusted: true
cask "font-bricolage-grotesque"
cask "font-fraunces"
cask "font-maple-mono-nf"
cask "font-recursive-mono-nerd-font"
cask "fujifilm-x-raw-studio"
cask "handbrake-app"
cask "helium-browser"
cask "okooo5km/tap/hipixel", trusted: true
cask "hyperconnect"
cask "hyperkey"
cask "iina"
cask "iriunwebcam"
cask "sozercan/repo/kaset", trusted: true
cask "keycastr"
cask "libreoffice"
cask "localsend"
cask "lunacy"
cask "markdown-preview"
cask "macsyzones"
cask "neodisk"
cask "nextcloud"
cask "obsidian"
cask "only-switch"
cask "orbstack"
cask "otty"
cask "phosphene"
cask "productdevbook/tap/portkiller", trusted: true
cask "rio"
cask "shotcut"
cask "sloth"
cask "space-rabbit"
cask "neighbor-z/swiftmtp/swiftmtp", trusted: true
cask "syntax-highlight", args: { skip_cask_deps: true, install_options: ["--no-quarantine"] }
cask "tablepro"
cask "tailscale-app"
cask "the-unarchiver"
cask "abue-ammar/tinycast/tinycast@beta", trusted: true
cask "transmission"
cask "vnc-viewer"
cask "vorssaint"
cask "vscodium"
cask "zed"
cask "zen"
