#!/usr/bin/env bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew update
brew upgrade

brew install bat
brew install eza
brew install fastfetch
brew install ffmpeg
brew install fnm
brew install fzf
brew install git
brew install pnpm
brew install scrcpy
brew install sheldon
brew install speedtest
brew install stow
brew install zoxide

brew install --cask kitty
brew install --cask raycast
brew install --cask transmission
