brew "bat"
brew "btop"
brew "oven-sh/bun/bun", trusted: true
brew "bjarneo/cliamp/cliamp", trusted: true
brew "diffnav"
brew "eza"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "eugene-babichenko/fixit/fixit", trusted: true
brew "fnm"
brew "fzf"
brew "git-delta"
brew "glow"
brew "mas"
brew "mole"
brew "pnpm"
brew "ripgrep"
brew "scrcpy"
brew "sheldon"
brew "stow"
brew "tealdeer"
brew "tmux"
brew "zoxide"

cask "appcleaner"
cask "aya"
cask "batfi"
cask "TheBoredTeam/boring-notch/boring-notch", trusted: true, args: { install_options: ["--no-quarantine"] }
cask "calendr"
cask "cloudflare-warp"
cask "deskpad"
cask "dockdoor"
cask "ente-auth"
cask "xykong/tap/flux-markdown", trusted: true
cask "font-bricolage-grotesque"
cask "font-comic-shanns-mono-nerd-font"
cask "font-departure-mono-nerd-font"
cask "font-fraunces"
cask "font-maple-mono-nf"
cask "font-recursive-mono-nerd-font"
cask "fujifilm-x-raw-studio"
cask "grandperspective"
cask "handbrake-app"
cask "helium-browser"
cask "okooo5km/tap/hipixel", trusted: true
cask "hyperkey"
cask "iina"
cask "iriunwebcam"
cask "sozercan/repo/kaset", trusted: true
cask "keycastr"
cask "libreoffice"
cask "localsend"
cask "lunacy"
cask "macsyzones"
cask "neohtop"
cask "nextcloud"
cask "obsidian"
cask "ocenaudio"
cask "only-switch"
cask "openmtp"
cask "orbstack"
cask "pearcleaner"
cask "productdevbook/tap/portkiller", trusted: true
cask "react-native-debugger"
cask "shotcut"
cask "sloth"
cask "stats"
cask "syntax-highlight", args: { skip_cask_deps: true, install_options: ["--no-quarantine"] }
cask "tablepro"
cask "tailscale-app"
cask "the-unarchiver"
cask "transmission"
cask "tuna"
cask "vnc-viewer"
cask "vorssaint"
cask "vscodium"
cask "zed"
cask "zen"

mas "Brightintosh", id: 6452471855
mas "Remote for Android TV", id: 1668755298
mas "System Color Picker", id: 1545870783
