#!/usr/bin/env bash

set -e

git submodule update --init --recursive

if [[ "$OSTYPE" == "darwin"* ]]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  brew update
  brew upgrade
  brew bundle
  stow --no-folding stow btop cliamp ghostty git opencode sheldon tmux tuna zed zsh
elif [[ -n "$TERMUX_VERSION" ]]; then
  pkg update
  pkg install -y $(grep -v '^#' termux-packages.sh | grep -v '^$')
  stow --no-folding stow btop git sheldon termux tmux zsh
else
  echo "Unsupported platform"
  exit 1
fi
