#!/usr/bin/env bash

set -e

git submodule update --init --recursive

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew update
brew upgrade
brew bundle

stow btop ghostty git sheldon tmux zsh
