shell = "zsh"

[plugins]

[plugins.spaceship]
github = "spaceship-prompt/spaceship-prompt"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
